export default {
  TEST_ACTION: 'HELLOWORLD.TEST_ACTION',
  TEST_REST_ACTION: 'HELLOWORLD.TEST_REST_ACTION',
  TEST_REST_ACTION_FAILED: 'ERROR.HELLOWORLD.TEST_REST_ACTION_FAILED',
  TEST_REST_ACTION_SUCCEED: 'HELLOWORLD.TEST_REST_ACTION_SUSSED',
};

export interface IStore {
  message: string;
  result: any;
}
